# ==========================================
# CONFIGURACIÓN GENERAL DEL PROYECTO
# ==========================================
spring.application.name=PrevDengue
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# ☁️ CONFIGURACIÓN NUBE (AZURE - PRODUCCIÓN)
# ==========================================
spring.datasource.url=jdbc:postgresql://prevdengue-db-prod.postgres.database.azure.com:5432/prevdengue_db?sslmode=require
spring.datasource.username=p1chulu
spring.datasource.password=Ctmre1234@

# ==========================================
# 💻 CONFIGURACIÓN LOCAL (DESARROLLO)
# (Para probar en tu PC, comenta las 3 líneas de arriba y descomenta las 3 de abajo)
# ==========================================
#spring.datasource.url=jdbc:postgresql://localhost:5432/dbprevdengue
#spring.datasource.username=postgres
#spring.datasource.password=1234

# ==========================================
# 🔐 SEGURIDAD JWT
# ==========================================
jwt.secret=unaClaveSecretaSegura123RAKDJLKASJDLKASJDLAKJDAKLJGKLANDJQKN

# ==========================================
# 🌐 PUERTO DEL SERVIDOR
# ==========================================
server.port=8080
